# Generated by Django 2.2.5 on 2019-09-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete='RESTRICT', to='textin.Survey'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete='RESTRICT', to='textin.Question'),
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('surveys', models.ManyToManyField(to='textin.Survey')),
            ],
        ),
    ]
