# Generated by Django 2.2.5 on 2019-09-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textin', '0003_auto_20190916_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='responder',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='textin.Responder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textin.Survey'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textin.Question'),
        ),
    ]
