# Generated by Django 2.2.6 on 2019-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textin', '0008_auto_20191003_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='pushed',
            field=models.BooleanField(default=False),
        ),
    ]
