# Generated by Django 2.2.6 on 2019-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textin', '0009_survey_pushed'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='start_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
