# Generated by Django 2.2.6 on 2019-10-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textin', '0010_survey_start_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='active_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='textin.Question'),
        ),
        migrations.AddField(
            model_name='survey',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_message',
            field=models.CharField(blank=True, default='That was the last question. Thank you for taking this survey!', max_length=500, null=True),
        ),
    ]
