# Generated by Django 2.2.6 on 2019-10-06 22:33
from datetime import date, timedelta
import json

from django.db import migrations

from textin.models import Responder
from textin.strings import ResponderStrings
from textin.util import SurveyLoader


def create_responder_details_surveys(apps, schema_editor):
    responder_details_qns = [{ 'body': ResponderStrings.get_responder_attr(attr),
                               'kind': 'text' } for attr in Responder.USER_SET_ATTRS]

    new_responder_details_survey = {
        'title': ResponderStrings.new_responder_details_title,
        'start_message': ResponderStrings.new_details_or_skip_instr
    }
    existing_responder_details_survey = {
        'title': ResponderStrings.update_responder_details_title,
        'start_message': ResponderStrings.existing_details_or_skip_instr
    }

    responder_details_common = {
        'end_message': "Thank you!",
        'start_date': date.today().isoformat(),
        # This survey is active for 100 years
        'end_date': (date.today() + timedelta(weeks=52*100)).isoformat(),
        'hidden': True,
        'questions': responder_details_qns
    }

    responder_details_surveys = [new_responder_details_survey, existing_responder_details_survey]
    for survey in responder_details_surveys:
        survey.update(responder_details_common)
        loader = SurveyLoader(json.dumps(survey))
        loader.load_survey()


class Migration(migrations.Migration):

    dependencies = [
        ('textin', '0011_auto_20191006_2233'),
    ]

    operations = [
        migrations.RunPython(create_responder_details_surveys)
    ]
